<?php 
include '../includes/header.php'; 
require_once('../../controllers/customer_controller.php');
require_once('../../controllers/product_controller.php');

// Fetch all customers
$customerController = new CustomerController();
$customers = $customerController->get_all_customers_ctr();

// Fetch all products
$productController = new ProductController();
$products = $productController->get_all_products_ctr();
?>

<div class="inv-container">
    <div class="inv-header">
        <div class="inv-title">New Invoice</div>
        <div class="inv-header-inputs">
            <div class="inv-input-group">
                <div class="date-input-container">
                    <label for="startDate">Start Date</label>
                    <input type="date" id="startDate" class="inv-form-input" required>
                </div>
                <div class="date-input-container">
                    <label for="dueDate">Due Date</label>
                    <input type="date" id="dueDate" class="inv-form-input" required>
                </div>
                <div class="inv-number-input">
                    <input type="text" id="invoiceNumber" class="inv-form-input" readonly>
                    <!--An invoice number is generated by getting the first three letters (all in caps) of the facility name from session, the year of generation and a random unique 9-digit number in this format e.g. ASH/24/123456789-->
                    <label>#INV</label>
                </div>
            </div>
        </div>
    </div>

    <div class="inv-info-section">
        <!-- Customer Information -->
        <div class="inv-card">
            <div class="inv-card-header">
                <h2>Patient Information</h2>
            </div>
            <!-- Customer Select Dropdown -->
            <div class="inv-customer-select">
                <select id="customerSelect" class="inv-form-input" onchange="showCustomerDetails(this.value)">
                    <option value="">Select a patient</option>
                    <?php foreach ($customers as $customer): ?>
                        <option value="<?php echo $customer['customer_id']; ?>">
                            <?php echo htmlspecialchars($customer['customer_firstname'] . ' ' . $customer['customer_lastname']); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <!-- Customer Details Form (initially hidden) -->
            <div id="customerDetails" class="inv-form-grid" style="display: none;">
                <input type="text" id="customerName" class="inv-form-input" readonly>
                <input type="email" id="customerEmail" class="inv-form-input" readonly>
                <input type="text" id="customerAddress" class="inv-form-input" readonly>
                <input type="text" id="customerCity" class="inv-form-input" readonly>
                <input type="text" id="customerCountry" class="inv-form-input" readonly>
                <input type="tel" id="customerPhone" class="inv-form-input" readonly>
            </div>
        </div>
    </div>

    <!-- Products Table -->
    <div class="inv-products-section">
        <table class="inv-products-table">
            <thead>
                <tr>
                    <th>Service</th>
                    <th>Qty</th>
                    <th>Price</th>
                    <th>Discount (%)</th>
                    <th>Sub Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="inv-serviceTableBody">
                <tr>
                    <td class="inv-product-cell">
                        <select class="inv-form-input inv-product-select" onchange="updateProductDetails(this)">
                            <option value="">Select a service</option>
                            <?php foreach ($products as $product): ?>
                                <option value="<?php echo htmlspecialchars(json_encode($product)); ?>">
                                    <?php echo htmlspecialchars($product['product_name']); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <td>
                        <input type="number" class="inv-form-input inv-qty-input" value="1" min="1" onchange="updateProductQuantity(this)">
                    </td>
                    <td>
                        <input type="number" class="inv-form-input inv-price-input" placeholder="0.00" step="0.01" readonly>
                    </td>
                    <td>
                        <input type="number" class="inv-form-input inv-discount-input" placeholder="0" min="0" max="100">
                    </td>
                    <td class="inv-subtotal">
                        <span>$0.00</span>  
                    </td>
                    <td class="inv-action-cell">
                        <button class="inv-remove-row-btn" title="Remove Service">×</button>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="inv-table-actions">
            <button class="inv-add-row-btn" id="addServiceBtn">+ Add Service</button>
        </div>
    </div>

    <!-- Totals Section -->
    <div class="inv-totals-section">
        <div class="inv-totals-container">
            <div class="inv-total-row" id="subtotal-row">
                <span>Total:</span>
                <span id="subtotal-display">$0.00</span>
            </div>
            <div class="inv-total-row" id="discount-row">
                <span>Discount:</span>
                <span id="discount-display">$0.00</span>
            </div>
            <div class="inv-total-row" id="fee-row">
                <span>Transaction fee (1%):</span>
                <span id="fee-display">$0.00</span>
            </div>
            <div class="inv-total-row inv-final-total" id="total-row">
                <span>Pay:</span>
                <span id="total-display">$0.00</span>
            </div>
        </div>
    </div>

    <div class="inv-form-actions">
        <button type="submit" class="inv-create-btn" id="createInvoiceBtn">Create Invoice</button>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="../../js/createinvoice.js"></script>

<?php include '../includes/footer.php'; ?>